### PR TITLE
removing getMarketInfoCache

### PR DESCRIPTION
**Pull request by kevinday**
I removed getMarketInfoCache since it's no longer needed: https://github.com/AugurProject/augur-core/pull/92

@tinybike has there been a change to make_api.py recently. Running it after I updated the latest compositeGetters changed much more than I expected in api.json.

### CODE REVIEW

**Comment by tinybike** [comment]
Are you specifying an input file?  It's supposed to preserve the send, returns, and mutable flags where they exist but it looks like it over wrote them instead.

**Comment by kevinday** [comment]
I didn't - I followed the instructions you posted previously (https://github.com/AugurProject/augur.js/issues/92#issuecomment-22887501 )and did `python make_api.py -o /path/to/augur-contracts/api.json`

From what I can tell though if no input file is given it just grabs it from `https://raw.githubusercontent.com/AugurProject/augur-contracts/master/api.json`, so I wouldn't expect specifying an input file to be a problem.

**Comment by tinybike** [comment]
Is your input file from the most recent augur-contracts push?  If not, it won't have the most recent info.  (Generally it's best to let it pull directly from the Github api.json.)

**Comment by kevinday** [comment]
I didn't specify an input file so it pulled from Github:

```
python make_api.py -o  ../../augur-contracts/api.json
Translated contracts: /Users/k_day/src/augur/augur-core/src-extern
Download api.json: https://raw.githubusercontent.com/AugurProject/augur-contracts/master/api.json
Contracts |################################| 35/35
Wrote contract API file: ../../augur-contracts/api.json
```

**Comment by tinybike** [comment]
Fixed a bug in `get_remote_api` (in make_api.py) -- it should work properly now.

**Comment by kevinday** [comment]
Thanks! Pushed new api.json and it looks much better now.

**Comment by tinybike** [comment]
Looks good!  Merging.

**Pull request merged**
