### PR TITLE
replacing augur contract address with one that only emits events, for testing…

### PR DESCRIPTION
**Pull request by epheph**
… augur-node before real augur contract gets deployed

@tinybike

### CODE REVIEW

**Comment by tinybike** [comment]
The event names should be capitalized, so that they match the naming conventions of the real contracts.

**Comment by epheph** [comment]
The event names are capitalized, it's the function names that have the lower first character

**Comment by tinybike** [comment]
...never mind, they are capitalized, I was looking at the function names.  My mistake :-1:

**Comment by epheph** [comment]
I did want to talk about this PR, do we want it merged? I've been `npm link`'ing it so that augur-node has something to read

**Comment by tinybike** [comment]
Merged it!  Sorry this took so long, I somehow didn't notice this PR when you put it up.

**Comment by tinybike** [comment]
Note that a couple of the logs have changed a bit in the interim (OrderCreated and OrderFilled).  It'd probably make sense to re-upload the event emitter contract + update this repo again so that everything matches 100%.

**Pull request merged**
